FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Lighthouse API

TBD

## Transfers [/transfers]

### List Transfers [GET]

+ Response 200 (application/json)
    + Attributes(array[Transfer])

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
            
## Data Structures

### Transfer

+ id: 566fac19-16ff-40ff-99d0-ad54bea25092 (UUID)
+ number: TR001 (string, required)
+ from (FacilityLink, required)
+ to (FacilityLink, required)

### FacilityLink

+ link (Link, required)

### Link

+ rel: suppliedBy (string, required)
+ href: /concept/uuid (string, required)
+ type: application/vnd.com.garnercorp.lighthouse.concept (string, required)

### UUID (string)