FORMAT: 1A
HOST: https://lighthouse.garnercorp.com/

# Lighthouse API

Amazing Lighthouse API

## Party [/parties/{id}]

### Get Party [GET]
+ Parameters
    + id: `566fac19-16ff-40ff-99d0-ad54bea25092` (UUID, required)
+ Response 200 (application/vnd.com.garnercorp.lighthouse.party+json;v=1)
    + Attributes(PartyIdentified) 

## Parties [/parties{?code}]

### Party querying [GET]
+ Parameters
    + code: SCINC (string, optional)
    
+ Response 200 (application/vnd.com.garnercorp.lighthouse.party+json;v=1)
    + Attributes(array[PartyIdentified]) 

## Facility [/facilities/{id}]

### Get Facility [GET]
+ Parameters
    + id: `566fac19-16ff-40ff-99d0-ad54bea25092` (UUID, required)
+ Response 200 (application/vnd.com.garnercorp.lighthouse.party+json;v=1)
    + Attributes(FacilityIdentified) 

## Facilities [/facilities{?code}]

### Facility querying [GET]
+ Parameters
    + code: BAM001 (string, optional)
    
+ Response 200 (application/vnd.com.garnercorp.lighthouse.party+json;v=1)
    + Attributes(array[FacilityIdentified]) 

## Group Transfer
 
### Create a new attained status [POST /transfers/{id}/attained-statuses]
+ Parameters
    + id: `566fac19-16ff-40ff-99d0-ad54bea25092` (UUID, required)
    
+ Request (application/vnd.com.garnercorp.lighthouse.status+json;v=1)
    + Attributes(Status)

+ Response 201 (application/vnd.com.garnercorp.lighthouse.status+json;v=1)
    + Headers 
    
            Location: /transfers/{id}/statuses/`126fac19-16ff-40ff-99d0-ad54bea250ff`
    + Attributes(StatusIdentified)
    
    
### Create a new forecasted status [POST /transfers/{id}/forecasted-statuses]
+ Parameters
    + id: `566fac19-16ff-40ff-99d0-ad54bea25092` (UUID, required)
    
+ Request (application/vnd.com.garnercorp.lighthouse.status+json;v=1)
    + Attributes(Status)

+ Response 201 (application/vnd.com.garnercorp.lighthouse.status+json;v=1)
    + Headers 
    
            Location: /transfers/{id}/statuses/`126fac19-16ff-40ff-99d0-ad54bea250ff`
    + Attributes(StatusIdentified)
    
## Transfers [/transfers{?number,referencedAsCode,referencedAsValue}]

### Transfer querying [GET]
+ Parameters
    + number: TR001 (string, optional)
    + referencedAsCode: `BILL_OF_LADING` (string, optional)
    + referencedAsValue: bill16 (string, optional)
    
+ Response 200 (application/vnd.com.garnercorp.lighthouse.transfer+json;v=1)
    + Attributes(array[TransferIdentified])

### Create a new transfer [POST]
+ Relation: create
+ Request (application/vnd.com.garnercorp.lighthouse.transfer+json;v=1)
       + Attributes(Transfer)
       
+ Response 201 (application/vnd.com.garnercorp.lighthouse.transfer+json;v=1)
    + Headers
    
            Location: /transfers/566fac19-16ff-40ff-99d0-ad54bea25092
            
    + Attributes(TransferIdentified)

## Group Material
 
### Create a new attained status [POST /materials/{id}/attained-statuses]
+ Parameters
    + id: `566fac19-16ff-40ff-99d0-ad54bea25092` (UUID, required)
    
+ Request (application/vnd.com.garnercorp.lighthouse.status+json;v=1)
    + Attributes(Status)

+ Response 201 (application/vnd.com.garnercorp.lighthouse.status+json;v=1)
    + Headers 
    
            Location: /materials/{id}/statuses/`126fac19-16ff-40ff-99d0-ad54bea250ff`
    + Attributes(StatusIdentified)
    
    
### Create a new forecasted status [POST /materials/{id}/forecasted-statuses]
+ Parameters
    + id: `566fac19-16ff-40ff-99d0-ad54bea25092` (UUID, required)
    
+ Request (application/vnd.com.garnercorp.lighthouse.status+json;v=1)
    + Attributes(Status)

+ Response 201 (application/vnd.com.garnercorp.lighthouse.status+json;v=1)
    + Headers 
    
            Location: /materials/{id}/statuses/`126fac19-16ff-40ff-99d0-ad54bea250ff`
    + Attributes(StatusIdentified)


## Materials [/materials{?materialId,referencedAsCode,referencedAsValue}]

### Material querying [GET]
+ Parameters
    + materialId: MAT1777 (string, optional)
    + referencedAsCode: `WORKPACK` (string, optional)
    + referencedAsValue: 1x45tthg (string, optional)
    
+ Response 200 (application/vnd.com.garnercorp.lighthouse.material+json;v=1)
    + Attributes(array[MaterialIdentified])

### Create a new material [POST]
+ Relation: create
+ Request (application/vnd.com.garnercorp.lighthouse.material+json;v=1)
       + Attributes(Material)
       
+ Response 201 (application/vnd.com.garnercorp.lighthouse.material+json;v=1)
    + Headers
    
            Location: /materials/566fac19-16ff-40ff-99d0-ad54bea25092
            
    + Attributes(MaterialIdentified)


## Data Structures

### PartyIdentified (Party)
+ id: `cc6fac19-16ff-40ff-99d0-ad54bea25091` (UUID)

### Party
+ name: Sorenson Controls (string, required)

### PartyQuery
+ id: `cc6fac19-16ff-40ff-99d0-ad54bea25091` (UUID)
+ code: SCINC (string)

### PartyLink
+ link (PartyLinkDetails, required)

### PartyLinkDetails
+ rel: tbd (string, required)
+ href: /parties/{id} (string, required)
+ type: application/vnd.com.garnercorp.lighthouse.party+json;v=1 (string, required)

### FacilityIdentified (Facility)
+ id: `ff6fac19-16ff-40ff-99d0-ad54bea25045` (UUID)

### Facility
+ name: Bamboo Base (string, required)
+ controlledBy (PartyIdentified)

### FacilityLink
+ link (FacilityLinkDetails, required)

### FacilityLinkDetails
+ rel: tbd (string, required)
+ href: /facilities/{id} (string, required)
+ type: application/vnd.com.garnercorp.lighthouse.facility+json;v=1 (string, required)

### TransferIdentified (Transfer)
+ id: `566fac19-16ff-40ff-99d0-ad54bea25092` (UUID)

### Transfer
+ number: TR001 (string, required)
+ from (FacilityLink, required)
+ to (FacilityLink, required)
+ attained (array[TransferStatusLink], optional)
+ forecasted (array[TransferStatusLink], optional)
+ referencedAs (array[TransferReferenceLink], optional)
+ carriedBy (PartyLink, optional)

### MaterialIdentified (Material)
+ id: `ab6fac19-16ff-40ff-99d0-ad54bea250ff` (UUID)

### TransferStatusLink
+ link (TransferStatusLinkDetails, required)

### TransferStatusLinkDetails
+ rel: tbd (string, required)
+ href: /transfers/{id}/statuses/{id} (string, required)
+ type: application/vnd.com.garnercorp.lighthouse.status+json;v=1 (string, required)

### TransferReferenceLink
+ link (TransferReferenceLinkDetails, required)

### TransferReferenceLinkDetails
+ rel: tbd (string, required)
+ href: /transfers/{id}/references/{id} (string, required)
+ type: application/vnd.com.garnercorp.lighthouse.reference+json;v=1 (string, required)

### Material
+ materialId: MAT1231 (string)
+ quantity: 12.5 (number)
+ description: water pump valve gasket (string)
+ suppliedBy (PartyLink, optional)
+ managedBy (PartyLink, optional)
+ observedBy (array[PartyLink], optional)
+ at (FacilityLink, optional)
+ attained (array[MaterialStatusLink])
+ forecasted (array[MaterialStatusLink])
+ referencedAs (array[MaterialReferenceLink])

### UUID (string)

### StatusIdentified (Status)
+ id: `566fac19-16ff-40ff-99d0-ad54bea25092` (UUID)
+ submittedOn: `2018-04-13T16:04:23Z` - UTC time

### Status
+ code: `CUSTOMS_CLEARED` (string)
+ occursOn: `2018-04-13T12:01:56` (string) - Local time

### MaterialStatusLink
+ link (MaterialStatusLinkDetails, required)

### MaterialStatusLinkDetails
+ rel: tbd (string, required)
+ href: /materials/{id}/statuses/{id} (string, required)
+ type: application/vnd.com.garnercorp.lighthouse.status+json;v=1 (string, required)

### ReferenceIdentified (Reference)
+ id: `566fac19-16ff-40ff-99d0-ad54bea25092` (UUID)

### Reference
+ code: WORKPACK (string)
+ value: WP123 (string)

### MaterialReferenceLink
+ link (MaterialReferenceLinkDetails, required)

### MaterialReferenceLinkDetails
+ rel: tbd (string, required)
+ href: /materials/{id}/references/{id} (string, required)
+ type: application/vnd.com.garnercorp.lighthouse.reference+json;v=1 (string, required)