FORMAT: 1A
HOST: https://lighthouse.garnercorp.com/

# Lighthouse API

Amazing Lighthouse API

## Party [/parties/{id}]

### Party [GET]
+ Parameters
    + id: `566fac19-16ff-40ff-99d0-ad54bea25092` (UUID, required)
+ Response 200 (application/vnd.com.garnercorp.lighthouse.party+json;v=1)
    + Attributes(PartyIdentified) 

## Parties [/parties{?code}]

### Party Querying [GET]
+ Parameters
    + code: SCINC (string)
    
+ Response 200 (application/vnd.com.garnercorp.lighthouse.party+json;v=1)
    + Attributes(PartyIdentified) 

## Transfers [/transfers]

### List Transfers [GET]

+ Response 200 (application/vnd.com.garnercorp.lighthouse.transfer+json;v=1)
    + Attributes(array[TransferIdentified])

### Create a New Transfer [POST]
+ Relation: create
+ Request (application/vnd.com.garnercorp.lighthouse.transfer+json;v=1)
       + Attributes(Transfer)
       
+ Response 201 (application/vnd.com.garnercorp.lighthouse.transfer+json;v=1)
    + Headers
    
            Location: /transfers/566fac19-16ff-40ff-99d0-ad54bea25092
            
    + Attributes(TransferIdentified)
            
## Data Structures

### PartyIdentified (Party)
+ id: `cc6fac19-16ff-40ff-99d0-ad54bea25091` (UUID)

### Party
+ name: Sorenson Controls (string, required)

### PartyQuery
+ id: `cc6fac19-16ff-40ff-99d0-ad54bea25091` (UUID)
+ code: SCINC (string)

### FacilityIdentified (Facility)
+ id: `ff6fac19-16ff-40ff-99d0-ad54bea25045` (UUID)

### Facility
+ name: Bamboo Base (string, required)
+ controlledBy (PartyIdentified)

### TransferIdentified (Transfer)
+ id: `566fac19-16ff-40ff-99d0-ad54bea25092` (UUID)

### Transfer
+ number: TR001 (string, required)
+ from (FacilityLink, required)
+ to (FacilityLink, required)

### FacilityLink

+ link (FacilityLinkDetails, required)

### FacilityLinkDetails

+ rel: tbd (string, required)
+ href: /facilities/uuid (string, required)
+ type: application/vnd.com.garnercorp.lighthouse.facility+json;v=1 (string, required)

### UUID (string)